// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB94CRXvRX1WP2mgeZZNhIIcZpSl3IO-sc',
    appId: '1:993324616296:web:a7b83df8615f3a301889dd',
    messagingSenderId: '993324616296',
    projectId: 'cinenest-e738b',
    authDomain: 'cinenest-e738b.firebaseapp.com',
    storageBucket: 'cinenest-e738b.firebasestorage.app',
    measurementId: 'G-9K9T4V60YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB50wibHlSccvPYHMtShu5IaVaVTz4uKaU',
    appId: '1:993324616296:android:b1faacd34244850b1889dd',
    messagingSenderId: '993324616296',
    projectId: 'cinenest-e738b',
    storageBucket: 'cinenest-e738b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFmP-7oGGO-0n4PtPltXyzZxpZ6_2-cn4',
    appId: '1:993324616296:ios:e46838e490b5ed031889dd',
    messagingSenderId: '993324616296',
    projectId: 'cinenest-e738b',
    storageBucket: 'cinenest-e738b.firebasestorage.app',
    iosBundleId: 'com.example.cineNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFmP-7oGGO-0n4PtPltXyzZxpZ6_2-cn4',
    appId: '1:993324616296:ios:e46838e490b5ed031889dd',
    messagingSenderId: '993324616296',
    projectId: 'cinenest-e738b',
    storageBucket: 'cinenest-e738b.firebasestorage.app',
    iosBundleId: 'com.example.cineNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB94CRXvRX1WP2mgeZZNhIIcZpSl3IO-sc',
    appId: '1:993324616296:web:3e5ab66fc2dcd8831889dd',
    messagingSenderId: '993324616296',
    projectId: 'cinenest-e738b',
    authDomain: 'cinenest-e738b.firebaseapp.com',
    storageBucket: 'cinenest-e738b.firebasestorage.app',
    measurementId: 'G-DG8YXDMEQD',
  );
}